{{- if .Values.notifier.smtp.passwordSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notifier.smtp.passwordSecret.name }}
  labels:
    {{- include "uniqlo-deal-hunter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.notifier.smtp.passwordSecret.key }}: {{ required "notifier.smtp.passwordSecret.value is required when create=true" .Values.notifier.smtp.passwordSecret.value | quote }}
{{- end }}
