{{- if eq (include "uniqlo-deal-hunter.smtpCreateSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uniqlo-deal-hunter.smtpSecretName" . }}
  labels:
    {{- include "uniqlo-deal-hunter.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "notifier.smtp.auth.password is required when auth.enabled=true and no existingSecret.name is set" .Values.notifier.smtp.auth.password | quote }}
{{- end }}
